const express = require("express");
const router = express.Router();
const userController = require("../controllers/userController");
const { verifyToken } = require("../middleware/authenticate");
// const fileUpload = require("../helper/S3Bucket");
const { uploads } = require("../middleware/imageUploads");
const multer = require('multer');
const upload = multer();

router.post("/signup", userController.createUser);
router.post("/signin", userController.signin);
router.get("/protected", verifyToken, userController.getUser);
router.post("/cover", [verifyToken,upload.single('image')],userController.uploadCoverImage);
router.post("/profile", [verifyToken,upload.single('image')],userController.uploadProfileImage);
router.post("/profileHeader", verifyToken, userController.profileHeader);
router.post("/profileOverview", verifyToken, userController.profileOverview);
router.post("/experience", verifyToken, userController.experience);
router.post("/education", verifyToken, userController.education);
router.post("/skill", verifyToken, userController.skill);
router.put("/CompanyProfile", verifyToken, userController.CompanyProfile);
router.get("/getUserProfile", verifyToken, userController.getUserProfile);
router.get("/getCompanyProfile", verifyToken, userController.getCompanyProfile);
router.get("/searchProject/:keyword", userController.searchProject);
router.get("/searchJob/:keyword", userController.searchJob);
router.get("/testAllUser", userController.testAllUser);
router.get("/freelancingDashboard", verifyToken, userController.freelancingDashboard);
router.get("/websiteCount", userController.websiteCount);
router.post("/sendEmail", userController.sendEmail);
router.post("/forgetPassword", userController.createResetEmail);
router.post("/verifyResetEmailCode", userController.verifyResetEmailCode);
router.put("/updatePassword", userController.updatePassword);
router.put("/resendCode", userController.resendCode);
// router.get("/Search" , userController.search);
// router.post("/DMNS", userController.DMNS); 
module.exports = router;
